export {
    UserIcon as UserIconOutline,
    UserGroupIcon as EmployeesOutline,
    ArrowLeftStartOnRectangleIcon as LogoutIcon,
    CalendarDaysIcon as CalendarIconOutline,
    ChevronUpDownIcon,
    Bars3Icon as MenuIcon,
    HomeIcon as HomeIconOutline,
    XMarkIcon,
    CheckIcon,
    BuildingOffice2Icon as RoomIconOutline,
    Squares2X2Icon as DashboardIconOutline,
    CogIcon as CogIconOutline,
    UserCircleIcon as UserCircleOutline,
} from "@heroicons/react/24/outline";

export {
    UserGroupIcon as EmployeesSolid,
    UserIcon as UserIconSolid,
    CalendarDaysIcon as CalendarIconSolid,
    BuildingOffice2Icon as RoomIconSolid,
    HomeIcon as HomeIconSolid,
    Squares2X2Icon as DashboardIconSolid,
    ClockIcon,
    CogIcon as CogIconSolid,
    PlusIcon,
    ChevronDoubleLeftIcon,
    InformationCircleIcon,
    UserCircleIcon as UserCircleSolid,
} from "@heroicons/react/24/solid";
